import os
import sys
import time
import subprocess
from pathlib import Path
from PyQt5.QtWidgets import (
    QApplication, QMainWindow, QWidget, QVBoxLayout, QHBoxLayout,
    QTextBrowser, QLineEdit, QPushButton, QProgressBar, QFileDialog, QLabel
)
from PyQt5.QtCore import QThread, pyqtSignal, QUrl, Qt
from PyQt5.QtGui import QDesktopServices

import sdr_shared

class RxWorker(QThread):
    """
    Background worker thread to monitor the incoming IPC binary file 
    generated by GNU Radio and forward received payload to the GUI.
    """
    message_received = pyqtSignal(str, str)  # (msg_type, payload_or_path)

    def __init__(self, rx_file):
        super().__init__()
        self.rx_file = rx_file
        self.running = True

    def run(self):
        last_mtime = 0
        while self.running:
            if os.path.exists(self.rx_file):
                try:
                    current_mtime = os.path.getmtime(self.rx_file)
                    if current_mtime > last_mtime:
                        last_mtime = current_mtime
                        with open(self.rx_file, "rb") as f:
                            data = f.read()
                        
                        if data:
                            # Simple header check for file vs text payload
                            if data.startswith(b"FILE:"):
                                header, content = data.split(b"\n", 1)
                                filename = header.decode("utf-8").split(":")[1]
                                self.message_received.emit("file", (filename, content))
                            else:
                                text_msg = data.decode("utf-8", errors="ignore")
                                self.message_received.emit("text", text_msg)
                except Exception as e:
                    print(f"[RxWorker Error]: {e}")
            time.sleep(0.1)

    def stop(self):
        self.running = False
        self.wait()


class TransceiverApp(QMainWindow):
    def __init__(self, node_id="A"):
        super().__init__()
        self.node_id = node_id
        
        # Native Linux temporary IPC paths for GNU Radio flowgraph
        self.tx_file = f"/tmp/node{self.node_id}_tx.bin"
        self.rx_file = f"/tmp/node{self.node_id}_rx.bin"
        
        # Persistent download directory in user's Linux home folder
        self.save_dir = os.path.expanduser(f"~/Downloads/node{self.node_id}_downloads")
        os.makedirs(self.save_dir, exist_ok=True)

        self.selected_file_path = None
        self.init_ui()

        # Start RX listener thread
        self.rx_worker = RxWorker(self.rx_file)
        self.rx_worker.message_received.connect(self.on_message_received)
        self.rx_worker.start()

    def init_ui(self):
        self.setWindowTitle(f"SDR Transceiver Node {self.node_id} (Linux)")
        self.resize(600, 500)

        central_widget = QWidget()
        self.setCentralWidget(central_widget)
        layout = QVBoxLayout(central_widget)

        # Chat / Log Window
        self.chat_display = QTextBrowser()
        self.chat_display.setOpenExternalLinks(False)
        self.chat_display.anchorClicked.connect(self.handle_link_click)
        layout.addWidget(self.chat_display)

        # File Attachment Bar
        file_layout = QHBoxLayout()
        self.file_label = QLabel("No file selected")
        self.btn_select_file = QPushButton("Attach File")
        self.btn_select_file.clicked.connect(self.select_file)
        file_layout.addWidget(self.btn_select_file)
        file_layout.addWidget(self.file_label)
        layout.addLayout(file_layout)

        # Text Input & Send Controls
        input_layout = QHBoxLayout()
        self.text_input = QLineEdit()
        self.text_input.setPlaceholderText("Type message here...")
        self.text_input.returnPressed.connect(self.send_payload)
        
        self.btn_send = QPushButton("Send")
        self.btn_send.clicked.connect(self.send_payload)
        
        input_layout.addWidget(self.text_input)
        input_layout.addWidget(self.btn_send)
        layout.addLayout(input_layout)

        # Transfer Progress Bar
        self.progress_bar = QProgressBar()
        self.progress_bar.setValue(0)
        layout.addWidget(self.progress_bar)

    def select_file(self):
        file_path, _ = QFileDialog.getOpenFileName(self, "Select File to Send", os.path.expanduser("~"))
        if file_path:
            self.selected_file_path = file_path
            self.file_label.setText(os.path.basename(file_path))

    def send_payload(self):
        # Priority: send attached file if selected, otherwise text message
        if self.selected_file_path:
            filename = os.path.basename(self.selected_file_path)
            with open(self.selected_file_path, "rb") as f:
                file_bytes = f.read()

            header = f"FILE:{filename}\n".encode("utf-8")
            payload = header + file_bytes
            
            self.write_to_tx(payload)
            self.chat_display.append(f"<b>[TX File]:</b> {filename} ({len(file_bytes)} bytes)")
            
            # Reset attachment state
            self.selected_file_path = None
            self.file_label.setText("No file selected")

        else:
            text = self.text_input.text().strip()
            if text:
                payload = text.encode("utf-8")
                self.write_to_tx(payload)
                self.chat_display.append(f"<b>[TX Text]:</b> {text}")
                self.text_input.clear()

    def write_to_tx(self, payload: bytes):
        """Writes binary payload to the IPC tx file for GNU Radio block consumption."""
        try:
            with open(self.tx_file, "wb") as f:
                f.write(payload)
            sdr_shared.tx_queue.put(payload)
        except Exception as e:
            self.chat_display.append(f"<font color='red'>[TX Error]: {e}</font>")

    def on_message_received(self, msg_type, data):
        if msg_type == "text":
            self.chat_display.append(f"<b>[RX Text]:</b> {data}")
        elif msg_type == "file":
            filename, file_bytes = data
            out_path = os.path.join(self.save_dir, filename)
            
            with open(out_path, "wb") as f:
                f.write(file_bytes)
            
            # Display clickable link in GUI log
            file_url = QUrl.fromLocalFile(out_path).toString()
            self.chat_display.append(f"<b>[RX File Saved]:</b> <a href='{file_url}'>{filename}</a>")

    def handle_link_click(self, url: QUrl):
        """
        Native Linux implementation to open received files with xdg-open.
        """
        local_path = url.toLocalFile()
        if os.path.exists(local_path):
            subprocess.run(["xdg-open", local_path], check=False)
        else:
            self.chat_display.append(f"<font color='red'>File not found: {local_path}</font>")

    def closeEvent(self, event):
        self.rx_worker.stop()
        event.accept()


if __name__ == "__main__":
    app = QApplication(sys.argv)
    
    # Optional node assignment via command line: python3 transceiver_app.py B
    node_id = sys.argv[1] if len(sys.argv) > 1 else "A"
    
    window = TransceiverApp(node_id=node_id)
    window.show()
    sys.exit(app.exec_())